# Generated by Django 4.2.4 on 2023-09-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_task_box_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
